/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Appeal: typeof import('./components/layout/appeal.vue')['default']
    Codemirror: typeof import('vue-codemirror')['Codemirror']
    ConnectionManager: typeof import('./components/socket/ConnectionManager.vue')['default']
    ConnectionState: typeof import('./components/socket/ConnectionState.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Loading: typeof import('./components/layout/loading.vue')['default']
    RustEditor: typeof import('./components/editor/rustEditor.vue')['default']
    Search: typeof import('./components/layout/search.vue')['default']
    ShellPlayer: typeof import('./components/player/shellPlayer.vue')['default']
    SocketForm: typeof import('./components/socket/socketForm.vue')['default']
  }
}
